# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Extract artifacts into staging directory
- task: CopyFiles@2
  displayName: 'Copy artifacts into staging'
  inputs:
    SourceFolder: 'target'
    Contents: '*.*ar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Upload content of staging directory into published domain
- task: PublishBuildArtifacts@1
  displayName: "Publish as artifact"
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'streamer-1.0-SNAPSHOT'
    publishLocation: Container